In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer


def pegar_dataframe_por_num_resposta(num_resposta: int):
    return pd.read_csv('perguntas_2019 - {} respostas - Pronto para uso (com bias).csv'.format(num_resposta))#%%



In [6]:
for num_respostas in range(3, 6):
    print("\n\n - - - - - Começando teste com {} respostas - - - - - \n\n".format(num_respostas))
    df = pegar_dataframe_por_num_resposta(num_respostas)

    colunas_respostas = ['pontos_resposta', 'tempo_resposta', 'user_reputation', 'tem_site_proprio', 'maestria_tags']
    colunas_relevantes = [c + str(resposta) for resposta in range(0, num_respostas) for c in colunas_respostas]

    x = df[colunas_relevantes]
    y = df['alvo']

    # Trocamos o valor default de variáveis em branco para -1 (antes era 0)
    simple_imputer = SimpleImputer(missing_values=np.NaN, strategy='constant', fill_value=-1)
    simple_imputer.fit(x)

    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.15)

    X_train = simple_imputer.transform(X_train)
    X_test = simple_imputer.transform(X_test)

    # Dessa vez realizamos o scalling!
    scaler = StandardScaler()
    scaler.fit(X_train)
    X_train = scaler.transform(X_train)
    X_test = scaler.transform(X_test)

    # Cria modelo
    mlp = MLPClassifier(hidden_layer_sizes=(3*(num_respostas-1), 3*(num_respostas-2)), max_iter=3000)
    mlp.fit(X_train, y_train.values.ravel())

    y_pred = mlp.predict(X_test)

    cm = confusion_matrix(y_test, y_pred)

    print(str(cm) + "\n")
    print(classification_report(y_test, y_pred))

    print("\n\n - - - - - Terminado teste com {} respostas - - - - - \n\n".format(num_respostas))



 - - - - - Começando teste com 3 respostas - - - - - 


[[23474  3265    68    58]
 [ 7509  4097    62     0]
 [ 1376   294   106     0]
 [  436    93    19    78]]

              precision    recall  f1-score   support

           0       0.72      0.87      0.79     26865
           1       0.53      0.35      0.42     11668
           2       0.42      0.06      0.10      1776
         700       0.57      0.12      0.20       626

    accuracy                           0.68     40935
   macro avg       0.56      0.35      0.38     40935
weighted avg       0.65      0.68      0.64     40935



 - - - - - Terminado teste com 3 respostas - - - - - 




 - - - - - Começando teste com 4 respostas - - - - - 


[[23422  3208   117    11    27]
 [ 7040  4535   137    11     0]
 [ 1154   451   160    13     0]
 [  219    93    22    21     0]
 [  174    36     7     0    77]]

              precision    recall  f1-score   support

           0       0.73      0.87      0.80     26785
     

C:\Users\Matheus\miniconda\envs\BigQueryEnv\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
